apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.17.0
        args:
          - -f
          - /mnt/locust/locustfile.py
          - --web-host
          - 0.0.0.0
          - --web-port
          - "8089"
          - --host
          - http://front-end.sock-shop.svc.cluster.local
        ports:
        - containerPort: 8089
        volumeMounts:
        - name: locustfile
          mountPath: /mnt/locust
      volumes:
      - name: locustfile
        configMap:
          name: locustfile-config
---
apiVersion: v1
kind: Service
metadata:
  name: locust-ui
  namespace: locust
spec:
  type: NodePort
  selector:
    app: locust
  ports:
  - name: http
    port: 8089
    targetPort: 8089
    nodePort: 30089
